### ISSUE TITLE
'config/**/*'をexcludeすることの是非

### ISSUE THREAD

**Issue by JunichiIto** [fjordllc/rubocop-fjord#7]
## 現状の問題点
https://github.com/fjordllc/rubocop-fjord/blob/v0.1.4/config/rails.yml#L9 で`'config/**/*'`をExcludeしているが、`config/routes.rb`など、手書きで編集するファイルもいくつかあるので、こういったファイルがチェック対象にならない。

## 解決策のオプション

1. `'config/**/*'`をExcludeしない
2. config内でExcludeするファイル、しないファイルを分ける
3. 現状維持（`'config/**/*'`はExcludeしたままにする）

どれも一長一短で悩ましい・・・。

**Comment by komagata** [comment]
僕はexcludeしちゃっていいと思いますー

**Comment by JunichiIto** [comment]
@komagata 了解です。それではもうしばらくexcludeのまま様子を見ましょうか。（選択肢3）
あまりにもconfig配下のコーディングミスが多いようであれば、再度検討する、ということで。
というわけでいったんクローズします〜。
